votd:
  announcement-enabled: true
  announcement-interval-minutes: 10
  announcement-format: "&6[VOTD] &e{reference} ({version}) &f{text}"
  bible-version: KJV
  message-format: "&6[VOTD] &e{reference} ({version}) &f{text}"
  api-url: "https://beta.ourmanna.com/api/v1/get/?format=json&order=daily&version=%s"
